# Generated by Django 5.0.14 on 2025-11-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional: YouTube URL to embed in the review page', null=True),
        ),
    ]
