# Generated by Django 5.0.14 on 2025-11-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
