# Generated by Django 5.0.14 on 2025-11-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional video URL, not currently used by embed logic below.', null=True),
        ),
    ]
